source "https://rubygems.org"

gem "cocoapods"
gem "motion-cocoapods"
# gem "ProMotion", :github => "clearsightstudio/ProMotion", :branch => "feature/delegate_improvements"
# gem "ProMotion" #, :github => "clearsightstudio/ProMotion", :branch => "version-0.7"
# gem "ProMotion", :github => "markrickert/ProMotion", :branch => "cell-accessory-switch-fix"
gem "ProMotion"
gem "twittermotion"
gem "formotion"
gem "bubble-wrap"
gem "sugarcube"
gem "awesome_print_motion"
gem "motion-testflight"