source "https://rubygems.org"

gem "cocoapods"
gem "motion-cocoapods"
gem "ProMotion"
gem "twittermotion"
gem "formotion"
gem "bubble-wrap"
gem "sugarcube"
gem "awesome_print_motion"
gem "motion-testflight"
