# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('1d010f0c240219bd97c8e4c40729e00b_MTc5NTc4MjAxMy0wMS0yOCAxNTowMTo1OC43MDY0MDM')
  end)
end
